// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/blacktrue/workflows-enable-inactive/services (interfaces: GithubService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/blacktrue/workflows-enable-inactive/models"
	gomock "github.com/golang/mock/gomock"
)

// MockGithubService is a mock of GithubService interface.
type MockGithubService struct {
	ctrl     *gomock.Controller
	recorder *MockGithubServiceMockRecorder
}

// MockGithubServiceMockRecorder is the mock recorder for MockGithubService.
type MockGithubServiceMockRecorder struct {
	mock *MockGithubService
}

// NewMockGithubService creates a new mock instance.
func NewMockGithubService(ctrl *gomock.Controller) *MockGithubService {
	mock := &MockGithubService{ctrl: ctrl}
	mock.recorder = &MockGithubServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGithubService) EXPECT() *MockGithubServiceMockRecorder {
	return m.recorder
}

// EnableWorkflow mocks base method.
func (m *MockGithubService) EnableWorkflow(arg0 int32, arg1, arg2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableWorkflow", arg0, arg1, arg2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnableWorkflow indicates an expected call of EnableWorkflow.
func (mr *MockGithubServiceMockRecorder) EnableWorkflow(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableWorkflow", reflect.TypeOf((*MockGithubService)(nil).EnableWorkflow), arg0, arg1, arg2)
}

// GetWorkflows mocks base method.
func (m *MockGithubService) GetWorkflows(arg0, arg1 string) ([]models.Workflow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWorkflows", arg0, arg1)
	ret0, _ := ret[0].([]models.Workflow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWorkflows indicates an expected call of GetWorkflows.
func (mr *MockGithubServiceMockRecorder) GetWorkflows(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWorkflows", reflect.TypeOf((*MockGithubService)(nil).GetWorkflows), arg0, arg1)
}
